src/objects/Route__c.object
<CustomObject>
    <fields>
        <fullName>Port_of_Destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Destination</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
        <relationshipName>Routes_end</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_of_Origin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Origin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes_start</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_date__c</fullName>
        <label>Arrival date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Departure date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>schedule_route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vessel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vessel</label>
        <referenceTo>Vessel__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Vessel__c.object
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FindSchedules.cls
/**
 * Created by POTERFI on 2/7/2022.
 */

public with sharing class FindSchedules {
    @AuraEnabled
    public static List<ScheduleWrapper> getSchedules(Date startDate, Date endDate, String departure, String arrival) {
        System.debug(startDate);
        List<Schedule__c> schedules = [
                SELECT Id,
                        Name,
                        Route__r.Name,
                        Vessel__r.Name,
                        Departure_date__c,
                        Arrival_date__c,
                        Route__r.Port_of_Origin__c,
                        Route__r.Port_of_Destination__c

                FROM Schedule__c
                WHERE
                Departure_date__c = :startDate
                AND Arrival_date__c = :endDate
                AND Route__r.Port_of_Origin__c = :departure
                AND Route__r.Port_of_Destination__c = :arrival
        ];

        List<ScheduleWrapper> wrappedSchedules = FindSchedules.getRelatedObjectsNames(schedules);

        return wrappedSchedules;
    }

    public static List<ScheduleWrapper> getRelatedObjectsNames(List<Schedule__c> scheds) {
        ScheduleWrapper wrapper = new ScheduleWrapper();
        List<ScheduleWrapper> wrappedSchedules = new List<ScheduleWrapper>();

        for (Schedule__c schedule : scheds) {
            wrapper.id = schedule.Id;
            wrapper.scheduleName = schedule.Name;
            wrapper.scheduleStartDate = schedule.Departure_date__c;
            wrapper.scheduleEndDate = schedule.Arrival_date__c;
            wrapper.routeName = schedule.Route__r.Name;
            wrapper.vesselName = schedule.Vessel__r.Name;
            wrappedSchedules.add(wrapper);
        }
        return wrappedSchedules;
    }


}