src/objects/Route__c.object
<CustomObject>
    <fields>
        <fullName>Port_of_Destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Destination</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
        <relationshipName>Routes_end</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_of_Origin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Origin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes_start</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_date__c</fullName>
        <label>Arrival date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Departure date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>schedule_route</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/FindRoutes.cls
/**
 * Created by POTERFI on 2/7/2022.
 */

public with sharing class FindRoutes {
    @AuraEnabled
    public static List<Schedule__c> getSchedules(Date startDate, Date endDate, String departure, String arrival){
        List<Schedule__c> schedules =
        [SELECT Id,
                Departure_date__c,
                Arrival_date__c,
                Route__r.Port_of_Origin__c,
                Route__r.Port_of_Destination__c
        FROM Schedule__c
        WHERE
        Departure_date__c =:startDate
        AND Arrival_date__c =:endDate
        AND Route__r.Port_of_Origin__c =:departure
        AND Route__r.Port_of_Destination__c =:arrival
        ];

     return schedules;
    }
}