src/objects/Route__c.object
<CustomObject>
    <fields>
        <fullName>Port_of_Destination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Destination</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes (Port of Destination)</relationshipLabel>
        <relationshipName>Routes_end</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Port_of_Origin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Port of Origin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Port</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Routes</relationshipLabel>
        <relationshipName>Routes_start</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_date__c</fullName>
        <label>Arrival date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Departure date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>schedule_route</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vessel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vessel</label>
        <referenceTo>Vessel__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <label>Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Vessel__c.object
<CustomObject>
    <label>Vessel</label>
    <nameField>
        <label>Ship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vessels</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/StringQueryBuilder.cls
/**
 * Created by POTERFI on 2/10/2022.
 */

public with sharing class StringQueryBuilder {


    public String generatedQuery;

    public String baseQuery = 'Select Id, Name, Route__r.Name, Vessel__r.Name, Departure_date__c, Arrival_date__c, Route__r.Port_of_Origin__c, Route__r.Port_of_Destination__c FROM Schedule__c';

    public String whereConditioner = ' Where ';

    public String buildQuery(Date departureDate, Date arrivalDate, String departurePort, String arrivalPort) {

        if ( ) {
            generatedQuery = baseQuery + whereConditioner + 'Departure_date__c in ' + '('+ departureDate + ')';
        }

        return generatedQuery;
    }


}